// Code generated by MockGen. DO NOT EDIT.
// Source: vendor/github.com/asecurityteam/logevent/logger.go

// Package v1 is a generated GoMock package.
package v1

import (
	reflect "reflect"

	"github.com/asecurityteam/logevent"
	gomock "github.com/golang/mock/gomock"
)

// MockLogger is a mock of Logger interface
type MockLogger struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerMockRecorder
}

// MockLoggerMockRecorder is the mock recorder for MockLogger
type MockLoggerMockRecorder struct {
	mock *MockLogger
}

// NewMockLogger creates a new mock instance
func NewMockLogger(ctrl *gomock.Controller) *MockLogger {
	mock := &MockLogger{ctrl: ctrl}
	mock.recorder = &MockLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockLogger) EXPECT() *MockLoggerMockRecorder {
	return m.recorder
}

// Debug mocks base method
func (m *MockLogger) Debug(event interface{}) {
	m.ctrl.Call(m, "Debug", event)
}

// Debug indicates an expected call of Debug
func (mr *MockLoggerMockRecorder) Debug(event interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debug", reflect.TypeOf((*MockLogger)(nil).Debug), event)
}

// Info mocks base method
func (m *MockLogger) Info(event interface{}) {
	m.ctrl.Call(m, "Info", event)
}

// Info indicates an expected call of Info
func (mr *MockLoggerMockRecorder) Info(event interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockLogger)(nil).Info), event)
}

// Warn mocks base method
func (m *MockLogger) Warn(event interface{}) {
	m.ctrl.Call(m, "Warn", event)
}

// Warn indicates an expected call of Warn
func (mr *MockLoggerMockRecorder) Warn(event interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warn", reflect.TypeOf((*MockLogger)(nil).Warn), event)
}

// Error mocks base method
func (m *MockLogger) Error(event interface{}) {
	m.ctrl.Call(m, "Error", event)
}

// Error indicates an expected call of Error
func (mr *MockLoggerMockRecorder) Error(event interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockLogger)(nil).Error), event)
}

// SetField mocks base method
func (m *MockLogger) SetField(name string, value interface{}) {
	m.ctrl.Call(m, "SetField", name, value)
}

// SetField indicates an expected call of SetField
func (mr *MockLoggerMockRecorder) SetField(name, value interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetField", reflect.TypeOf((*MockLogger)(nil).SetField), name, value)
}

// Copy mocks base method
func (m *MockLogger) Copy() logevent.Logger {
	ret := m.ctrl.Call(m, "Copy")
	ret0, _ := ret[0].(logevent.Logger)
	return ret0
}

// Copy indicates an expected call of Copy
func (mr *MockLoggerMockRecorder) Copy() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Copy", reflect.TypeOf((*MockLogger)(nil).Copy))
}